127.0.0.1 - - [04/Sep/2025 15:13:31] "GET /api/health HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:13:59] "GET /admin/login.html HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:13:59] "GET /assets/css/style.css HTTP/1.1" 304 -
127.0.0.1 - - [04/Sep/2025 15:14:16] "GET /admin/login.html HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:14:16] "GET /assets/css/style.css HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:14:16] "GET /assets/img/logo.gif HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:14:16] "GET /assets/js/auth.js HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:14:16] "GET /assets/js/auth.js HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:14:21] "GET /admin/index.html HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:14:21] "GET /assets/js/admin.js HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:14:21] "GET /api/admin-config HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:14:21] "GET /api/health HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:14:24] "GET /admin/products.html HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:14:24] "GET /api/admin-config HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:14:24] "GET /api/health HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:22:39] "GET /admin/login.html HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:22:39] "GET /assets/js/auth.js HTTP/1.1" 304 -
127.0.0.1 - - [04/Sep/2025 15:22:39] "GET /api/admin-config HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:22:39] "GET /api/admin-config HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:22:45] "GET /api/admin-config HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:22:45] "GET /api/health HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:22:49] "GET /api/admin-config HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:22:49] "GET /api/health HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 62052)
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/server.py", line 660, in __init__
    super().__init__(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/server.py", line 434, in handle
    self.handle_one_request()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/server.py", line 422, in handle_one_request
    method()
  File "/Users/hosonokai/Desktop/handicraft-green/server.py", line 130, in do_POST
    if not fileitem or not fileitem.filename:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/cgi.py", line 582, in __bool__
    raise TypeError("Cannot be converted to bool.")
TypeError: Cannot be converted to bool.
----------------------------------------
127.0.0.1 - - [04/Sep/2025 15:27:40] "POST /api/products HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:27:53] "POST /api/products HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:27:55] "POST /api/admin-products HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:41:59] "GET /api/health HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2025 15:41:59] "GET /api/health HTTP/1.1" 200 -
